@enum SENSE MAXIMIZE = -1 FEASIBILITY = 0 MINIMIZE = 1
@enum BASIS_STATUS UNDEFINED BASIC NONBASIC_AT_LOWER_BOUND NONBASIC_AT_UPPER_BOUND NONBASIC
@enum DUAL_STATUS ACTIVE INACTIVE
@enum CROSSOVER_STATUS UNSTARTED SUCCEEDED PRIMAL_SUCCEEDED PRIMAL_FAILED DUAL_SUCCEEDED DUAL_FAILED DUAL_SKIPPED LINEAR_IND_SUCCEEDED LINEAR_IND_FAILED REACHED_ITERATION_LIMIT REACHED_TIME_LIMIT
@enum PRIMAL_PUSH_METHOD P_PDLP P_OLS P_HYBRID
@enum DUAL_PUSH_METHOD D_PDLP D_OLS D_HYBRID
@enum OLS_METHOD OLS_QR OLS_LSMR OLS_AUTO OLS_PCG
@enum OPTIMALITY_NORM L_INF L_2